### ISSUE TITLE
Replace Access as a data storage medium

### ISSUE THREAD

**Issue by Amaras** [pascalaubry/papi-web#19]
This is a tracking issue for the replacement of the JET database as a storage medium.

### Database structure (defined in #807)

- [x] Create new Players/Pairings data base schemas
- [x] Consider in the structure that board numbers should be stored and remain unchanged when adding new pairings
- [x] It should be possible to assign players to multiple tournaments
- [x] The start_rank, should be stored on the Player/Tournament table
- [x] Some data, such as the rating and rating type should duplicated into the Player/Tournament table in order to a handle Grand Prix type events

### Code refactoring

- [x] Make the code entire code base handle `Stored` data classes for players, pairings and boards (#807)
- [x] Handle the new store via `EventDatabase` instead of `PapiDatabase` (#866)
  - [x] Add `create` - `update` - `delete`  methods for each table in `EventDatabase`
  - [x] Replace all `PapiDatabase` core usages
- [x] Refactor `Player` and `TournamentPlayer` (while considering multi-tournament) (#807)
- [x] Pairing generation needs updating (#807)
- [x] Remove the file related fields from the DB
  - [x] Migration needs to convert papi files to the new format with help from `papi-converter`
- [x] use json (formatted like the `papi-converter`) instead of .papi files for tests
- [x] use papi-converter to download the local FFE database
- [x] FFE upload needs to generate Papi files with help from `papi-converter`
- [x] ChessEvent plugin needs updating
- [x] All Access libraries should be removed
- [x] replace `StoredResult` by `StoredBoard.last_result_update`
- [x] replace `StoredIllegalMoves` by `StoredPairing.illegal_moves: int`

### UI changes

- [x] Tournament export to Papi option - required for norms etc, and maybe to get out of sticky situations if we have bugs :)
- [x] Tournament import from Papi (see #808)
- [x] Duplicating an event should provide an option to include players
- [ ] Multiple tournament assignment (3.x > 3.0)
- [ ] None-Papi Tie breaks selection (3.x > 3.0)
  - [ ] The FFE plugin should warn that papi export will be disabled if non legacy tie-breaks are selected
